# fly.toml app configuration file generated for koerza-processor on 2026-03-06T22:06:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'koerza-processor'
primary_region = 'ams'

[build]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
